// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs(
    ID, JOBID, URL
) VALUES (
    $1, $2, $3
)
`

type CreateJobParams struct {
	ID    uuid.UUID
	Jobid string
	Url   string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob, arg.ID, arg.Jobid, arg.Url)
	return err
}

const markCrawled = `-- name: MarkCrawled :exec
UPDATE jobs
SET crawled = true
WHERE url = $1
`

func (q *Queries) MarkCrawled(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, markCrawled, url)
	return err
}

const markFetched = `-- name: MarkFetched :exec
UPDATE jobs
SET fetched = true
WHERE url = $1
`

func (q *Queries) MarkFetched(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, markFetched, url)
	return err
}

const markTokenized = `-- name: MarkTokenized :exec
UPDATE jobs
SET tokenized = true
WHERE url = $1
`

func (q *Queries) MarkTokenized(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, markTokenized, url)
	return err
}
