// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Job struct {
	ID        uuid.UUID
	Jobid     string
	Url       string
	Fetched   bool
	Crawled   bool
	Tokenized bool
	Indexed   bool
}

type ParsedHtml struct {
	ID          uuid.UUID
	Jobid       string
	Url         string
	Title       string
	Description string
	Headings    string
	Paragraphs  string
	Links       string
}

type RawHtml struct {
	ID    uuid.UUID
	Jobid string
	Url   string
	Html  string
}
