// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Job struct {
	ID        uuid.UUID
	Jobid     string
	Url       string
	Fetched   bool
	Crawled   bool
	Tokenized bool
	Indexed   bool
}

type RawHtml struct {
	ID    uuid.UUID
	Jobid string
	Url   string
	Html  string
}
