// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parsed_html.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addParsedHTML = `-- name: AddParsedHTML :one
INSERT INTO parsed_html(
    id , jobId, url, title, description, headings, paragraphs, links
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, jobid, url, title, description, headings, paragraphs, links
`

type AddParsedHTMLParams struct {
	ID          uuid.UUID
	Jobid       string
	Url         string
	Title       string
	Description string
	Headings    string
	Paragraphs  string
	Links       string
}

func (q *Queries) AddParsedHTML(ctx context.Context, arg AddParsedHTMLParams) (ParsedHtml, error) {
	row := q.db.QueryRowContext(ctx, addParsedHTML,
		arg.ID,
		arg.Jobid,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.Headings,
		arg.Paragraphs,
		arg.Links,
	)
	var i ParsedHtml
	err := row.Scan(
		&i.ID,
		&i.Jobid,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Headings,
		&i.Paragraphs,
		&i.Links,
	)
	return i, err
}
