// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_html.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addHtml = `-- name: AddHtml :one
INSERT INTO raw_html(id, jobid, url, html)
VALUES ($1, $2, $3, $4)
RETURNING id, jobid, url, html
`

type AddHtmlParams struct {
	ID    uuid.UUID
	Jobid string
	Url   string
	Html  string
}

func (q *Queries) AddHtml(ctx context.Context, arg AddHtmlParams) (RawHtml, error) {
	row := q.db.QueryRowContext(ctx, addHtml,
		arg.ID,
		arg.Jobid,
		arg.Url,
		arg.Html,
	)
	var i RawHtml
	err := row.Scan(
		&i.ID,
		&i.Jobid,
		&i.Url,
		&i.Html,
	)
	return i, err
}
